import {Armor, Shield, Sourcebook, Ware, Weapon, CP,SP,EP,GP,PP, Roll} from './core';

// PHB construction
var sb : Sourcebook = new Sourcebook("Player's Handbook","PHB").author('Wizards of the Coast');

// Ware construction
let weapons = [
new Weapon('Club','149').classify('WC').sell(SP(1)).light().lb(2).dmgtype('Bludgeoning').dmg(4).simple(),
new Weapon('Dagger','149').classify('WB').classify('WT').sell(GP(2)).finesse().light().thrown('20/60').lb(1).dmgtype('Piercing').dmg(4).simple(),
new Weapon('Greatclub','149').classify('WC').sell(SP(2)).twohanded().lb(10).dmgtype('Bludgeoning').dmg(8).simple(),
new Weapon('Handaxe','149').classify('WX').sell(GP(5)).dmg(6).dmgtype('Slashing').lb(2).light().thrown('20/60').simple(),
new Weapon('Javelin','149').classify('WT').sell(SP(5)).dmg(6).dmgtype('Piercing').lb(2).thrown('30/120').simple(),
new Weapon('Light Hammer', '149').classify('WH').sell(GP(2)).dmg(4).dmgtype('Bludgeoning').lb(2).light().thrown('20/60').simple(),
new Weapon('Mace','149').classify('WC').sell(GP(5)).dmg(6).dmgtype('Bludgeoning').lb(4).simple(),
new Weapon('Quarterstaff','149').classify('WV').sell(SP(2)).dmg(6).dmgtype('Bludgeoning').lb(4).versatile(8).simple(),
new Weapon('Sickle','149').classify('WB').sell(GP(1)).dmg(4).dmgtype('Slashing').lb(2).light().simple(),
new Weapon('Spear', '149').classify('WP').sell(GP(1)).dmg(6).dmgtype('Piercing').lb(3).thrown('20/60').versatile(8).simple(),
new Weapon('Crossbow, Light','149').classify('WR000').sell(GP(25)).dmg(8).dmgtype('Piercing').lb(5).ammunition('80/320').loading().twohanded().simple(),
new Weapon('Dart','149').classify('WT').sell(CP(5)).dmg(4).dmgtype('Piercing').lb(0.25).finesse().thrown('20/60').simple(),
new Weapon('Shortbow','149').classify('WR000').sell(GP(25)).dmg(6).dmgtype('Piercing').lb(2).ammunition('80/320').twohanded().simple(),
new Weapon('Sling','149').classify('WR').sell(SP(1)).dmg(4,'Bludgeoning').ammunition('30/120').simple(),
new Weapon('Battleaxe','149').classify('WX').sell(GP(10)).dmg(8,'Slashing').lb(4).versatile(10).martial(),
new Weapon('Flail','149').classify('WC').sell(GP(10)).dmg(8,'Bludgeoning').lb(2).martial(),
new Weapon('Glaive','149').classify('WP').sell(GP(20)).dmg(10,'Slashing').lb(6).heavy().reach().twohanded().martial(),
new Weapon('Greataxe','149').classify('WX').sell(GP(30)).dmg(12,'Slashing').lb(7).heavy().twohanded().martial(),
new Weapon('Greatsword','149').classify('WB').sell(GP(50)).dmg(new Roll().D6(2),'Slashing').lb(6).heavy().twohanded().martial(),
new Weapon('Halberd','149').classify('WP').sell(GP(20)).dmg(10,'Slashing').lb(6).heavy().reach().twohanded().martial(),
new Weapon('Lance','149').classify('WP').sell(GP(10)).dmg(12,'Piercing').lb(6).reach().special('').martial(),
new Weapon('Longsword','149').classify('WB').sell(GP(15)).dmg(8,'Slashing').lb(3).versatile(10).martial(),
new Weapon('Maul','149').classify('WC').sell(GP(10)).dmg(new Roll().D6(2),'Bludgeoning').lb(10).heavy().twohanded().martial(),
new Weapon('Morningstar','149').classify('WC').sell(GP(15)).dmg(8,'Piercing').lb(4).martial(),
new Weapon('Pike','149').classify('WP').sell(GP(5)).dmg(10,'Piercing').lb(18).heavy().reach().twohanded().martial(),
new Weapon('Rapier','149').classify('WB').sell(GP(25)).dmg(8,'Piercing').lb(2).finesse().martial(),
new Weapon('Scimitar','149').classify('WB').sell(GP(25)).dmg(6,'Slashing').lb(3).finesse().light().martial(),
new Weapon('Shortsword','149').classify('WB').sell(GP(10)).dmg(6,'Piercing').lb(2).finesse().light().martial(),
new Weapon('Trident','149').classify('WP').sell(GP(5)).dmg(6,'Piercing').lb(4).thrown('20/60').versatile(8).martial(),
new Weapon('War Pick','149').classify('WZ').sell(GP(5)).dmg(8,'Piercing').lb(2).martial(),
new Weapon('Warhammer','149').classify('WH').sell(GP(15)).dmg(8,'Bludgeoning').lb(2).versatile(10).martial(),
new Weapon('Whip','149').classify('WZ').sell(GP(2)).dmg(4,'Slashing').lb(3).finesse().reach().martial(),
new Weapon('Blowgun','149').classify('WR').sell(GP(10)).dmg(new Roll().MOD(1),'Piercing').lb(1).ammunition('25/100').loading().martial(),
new Weapon('Crossbow, Hand','149').classify('WR000').sell(GP(75)).dmg(6,'Piercing').lb(3).ammunition('30/120').light().loading().martial(),
new Weapon('Crossbow, Heavy','149').classify('WR000').sell(GP(50)).dmg(10,'Piercing').lb(18).ammunition('100/400').heavy().loading().twohanded().martial(),
new Weapon('Longbow','149').classify('WR000').sell(GP(50)).dmg(8,'Piercing').lb(2).ammunition('150/600').heavy().twohanded().martial(),
new Weapon('Net','149').classify('WT').sell(GP(1)).dmg(new Roll(),'Bludgeoning').lb(3).special('').thrown('5/15').martial(),

new Weapon('Arcane Focus, Crystal',"150").sell(10).lb(1).classify("WF000"),
new Weapon('Arcane Focus, Orb','150').sell(20).lb(3).classify("WF000"),
new Weapon('Arcane Focus, Rod','150').sell(10).lb(2).classify("WF000"),
new Weapon('Arcane Focus, Staff','150').sell(5).lb(4).classify("WF000"),
new Weapon('Arcane Focus, Wand','150').sell(10).lb(1).classify("WF000"),
new Weapon('Druidic Focus, Sprig of Mistletoe','150').sell(1).classify("WF100"),
new Weapon('Druidic Focus, Totem','150').sell(1).classify("WF100"),
new Weapon('Druidic Focus, Wooden Staff','150').sell(5).lb(4).classify("WF100"),
new Weapon('Druidic Focus, Yew Wand','150').sell(10).lb(1).classify("WF100"),
new Weapon('Holy Symbol, Amulet','150').sell(5).lb(1).classify("WF200"),
new Weapon('Holy Symbol, Emblem','150').sell(5).classify("WF200"),
new Weapon('Holy Symbol, Reliquary','150').sell(5).lb(2).classify("WF200"),

new Weapon('Arrows','150').sell(GP(1).measure("20")).lb(1).classify("WA"),
new Weapon('Blowgun Needles','150').sell(GP(1).measure("50")).lb(1).classify("WA"),
new Weapon('Crossbow bolts','150').sell(GP(1).measure("20")).lb(1.5).classify("WA"),
new Weapon('Sling bullets','150').sell(CP(4).measure("20")).lb(1.5).classify("WA")
]

let armors = [
    new Armor('Padded Armor','145','Light').sell(GP(5)).ac(11,'Dexterity').disadvantage('Stealth').lb(8).classify("AB"),
    new Armor('Leather Armor','145','Light').sell(GP(10)).ac(11,'Dexterity').lb(10).classify("AB"),
    new Armor('Studded Leather Armor','145','Light').sell(45).ac(12,'Dexterity').lb(13).classify("AB"),

    new Armor('Hide Armor','145','Medium').sell(10).ac(12,'Dexterity',2).lb(12).classify("AB"),
    new Armor('Chain Shirt','145','Medium').sell(50).ac(13,'Dexterity',2).lb(20).classify("AC"),
    new Armor('Scale Mail','145','Medium').sell(50).ac(14,'Dexterity',2).disadvantage('Stealth').lb(45).classify("AB"),
    new Armor('Breastplate','145','Medium').sell(400).ac(14,'Dexterity',2).lb(20).classify("AC"),
    new Armor('Half Plate Armor','145','Medium').sell(750).ac(15,'Dexterity',2).disadvantage('Stealth').lb(40).classify("AC"),

    new Armor('Ring Mail','145','Heavy').sell(30).ac(14).disadvantage('Stealth').lb(40).classify('AB'),
    new Armor('Chain Mail','145','Heavy').sell(75).ac(16).strReq(13).disadvantage('Stealth').lb(55).classify("AB"),
    new Armor('Splint Armor','145','Heavy').sell(200).ac(17).strReq(15).disadvantage('Stealth').lb(60).classify("AB"),
    new Armor('Plate Armor','145','Heavy').sell(1500).ac(18).strReq(15).disadvantage('Stealth').lb(65).classify("AB"),

    new Shield('Shield','145').sell(10).bonusAC(2).lb(6).classify("AS")
]

let gear = [
    new Ware("Abacus",'150').sell(2).lb(2).classify("TC"),
    new Ware('Acid','150').sell(GP(25).measure("vial")).lb(1).classify('PO'),
    new Ware("Alchemist's Fire",'150').sell(GP(50).measure('flask')).lb(1).classify('PO'),
    new Ware('Antitoxin','150').sell(GP(50).measure('vial')).classify('ZM'),
    new Ware("Backpack","150").sell(2).lb(5).classify("ZC"),
    new Ware('Ball Bearings','150').sell(GP(1).measure('1000')).lb(2).classify('ZT'),
    new Ware("Barrel","150").sell(2).lb(70).classify("ZC"),
    new Ware('Basket','150').sell(SP(4)).lb(2).classify("ZC"),
    new Ware('Bedroll','150').sell(1).lb(7).classify('ZS'),
    new Ware('Bell, Small','150').sell(1).classify('ZT'),
    new Ware("Blanket","150").sell(SP(5)).lb(3).classify("ZS"),
    new Ware('Block and tackle','150').sell(1).lb(5).classify('ZT'),
    new Ware('Book','150').sell(25).lb(5).classify('B'),
    new Ware("Bottle, glass",'150').sell(2).lb(2).classify("ZC"),
    new Ware('Bucket','150').sell(CP(5)).lb(2).classify("ZC"),
    new Ware('Caltrops','150').sell(GP(1).measure('20')).lb(2).classify('ZT'),
    new Ware('Candle','150').sell(CP(1)).classify('ZL'),
    new Ware('Case, Crossbow Bolt','150').sell(1).lb(1).classify('TS'),
    new Ware('Case, Map or Scroll','150').sell(1).lb(1).classify('TS'),
    new Ware('Chain','150').sell(GP(5).measure('10 feet')).lb(10).classify("ZR"),
    new Ware('Chalk','150').sell(CP(1).measure('piece')).classify('TC'),
    new Ware('Chest','150').sell(5).lb(25).classify('TS'),
    new Ware("Climber's Kit","150").sell(25).lb(12).classify("TK"),
    new Ware('Clothes, common','150').sell(SP(5)).lb(3).classify('O'),
    new Ware('Clothes, costume','150').sell(5).lb(4).classify('OC'),
    new Ware('Clothes, fine','150').sell(15).lb(6).classify('OF'),
    new Ware("Clothes, traveler's",'150').sell(2).lb(4).classify('O'),
    new Ware('Component Pouch','150').sell(25).lb(2).classify('TS'),
    new Ware('Crowbar','150').sell(2).lb(5).classify('T'),
    new Ware('Fishing tackle','150').sell(1).lb(4).classify('T'),
    new Ware('Flask','150').sell(CP(2)).lb(1).classify('ZC'),
    new Ware('Grappling Hook','150').sell(2).lb(4).classify('T'),
    new Ware('Hammer','150').sell(1).lb(3).classify('T'),
    new Ware('Hammer, sledge','150').sell(2).lb(10).classify('T'),
    new Ware('Holy water','150').sell(GP(25).measure('flask')).lb(1).classify('MP'),
    new Ware("Healer's Kit","150").sell(5).lb(3).classify("TK"),
    new Ware('Hourglass','150').sell(25).lb(1).classify('TT'),
    new Ware('Hunting trap','150').sell(5).lb(25).classify('ZT'),
    new Ware('Ink','150').sell(GP(10).measure('oz.')).classify('TC'),
    new Ware('Ink pen','150').sell(CP(2)).classify('TC'),
    new Ware('Jug','150').sell(CP(2)).lb(4).classify('TS'),
    new Ware('Ladder','150').sell(SP(1).measure('10-foot')).lb(25).classify('TN'),
    new Ware('Lamp','150').sell(SP(5)).lb(1).classify('TL','ZL'),
    new Ware('Lantern, bullseye','150').sell(10).lb(2).classify('TL','ZL'),
    new Ware('Lantern, hooded','150').sell(5).lb(2).classify('TL','ZL'),
    new Ware('Lock','150').sell(10).lb(1).classify('TS'),
    new Ware('Magnifying glass','150').sell(100).classify('TC'),
    new Ware('Manacles','150').sell(2).lb(6).classify('ZT'),
    new Ware('Mess kit','150').sell(SP(2)).lb(1).classify('TK'),
    new Ware('Mirror, steel','150').sell(5).lb(0.5).classify('T'),
    new Ware('Oil','150').sell(SP(1).measure('flask')).lb(1).classify('PO'),
    new Ware('Paper','150').sell(SP(2).measure('sheet')).classify('TC'),
    new Ware('Parchment','150').sell(SP(1).measure('sheet')).classify('TC'),
    new Ware('Perfume','150').sell(GP(5).measure('vial')).classify('P'),
    new Ware("Pick, miner's",'150').sell(2).lb(10).classify('T'),
    new Ware('Pitcher','150').sell(CP(2)).lb(4).classify('TS'),
    new Ware('Piton','150').sell(CP(5)).lb(0.25).classify('TN'),
    new Ware('Poison, basic','150').sell(GP(100).measure('vial')).classify('PS'),
    new Ware('Pole','150').sell(CP(5).measure('10-foot')).lb(7).classify('TN','ZT'),
    new Ware('Pot, iron','150').sell(2).lb(10).classify('FE'),
    new Ware('Potion of healing','150').sell(50).lb(0.5).classify('MPP'),
    new Ware('Pouch','150').sell(SP(5)).lb(1).classify('TS'),
    new Ware('Quiver','150').sell(1).lb(1).classify('TS','WA'),
    new Ware('Ram, portable','150').sell(4).lb(35).classify('WG'),
    new Ware('Rations','150').sell(SP(5).measure('day')).lb(2).classify('FP'),
    new Ware('Robes','150').sell(1).lb(4).classify('OO'),
    new Ware('Rope, hempen','150').sell(GP(1).measure('50 feet')).lb(10).classify('ZR'),
    new Ware('Rope, silk','150').sell(GP(10).measure('50 feet')).lb(5).classify('ZR'),
    new Ware('Sack','150').sell(CP(1)).lb(0.5).classify("ZC"),
    new Ware("Scale, merchant's",'150').sell(5).lb(3).classify('TC'),
    new Ware('Sealing wax','150').sell(SP(5)).classify('TC'),
    new Ware('Shovel','150').sell(2).lb(5).classify('T'),
    new Ware('Signal whistle','150').sell(CP(5)).classify('T'),
    new Ware('Signet ring','150').sell(5).classify('OJ','TC'),
    new Ware('Soap','150').sell(CP(2)).classify('T','Z'),
    new Ware('Spellbook','150').sell(50).lb(3).classify('BA'),
    new Ware('Spikes, iron','150').sell(GP(1).measure('10')).lb(5).classify('ZT'),
    new Ware('Spyglass','150').sell(1000).lb(1).classify('TN'),
    new Ware('Tankard','150').sell(CP(2)).lb(1).classify('ZC'),
    new Ware('Tent, two-person','150').sell(2).lb(20).classify('ZS'),
    new Ware('Tinderbox','150').sell(SP(5)).lb(1).classify('TL','ZL'),
    new Ware('Torch','150').sell(CP(1)).lb(1).classify('TL','ZL'),
    new Ware('Vial','150').sell(1).classify('TS'),
    new Ware('Waterskin (full)','150').sell(SP(2)).lb(5).classify('FE','TS','ZC'),
    new Ware('Whetstone','150').sell(CP(1)).lb(1).classify('T')
]

sb.multistock(weapons).multistock(armors).multistock(gear).write();
//console.log(JSON.stringify(sb.shop("WF")));